import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="coffee">
      <body className={`${inter.className} max-w-[80%] flex flex-col  justify-center mx-auto py-4`}>{children}</body>
    </html>
  )
}
